const {initializeApp,cert,getApps}=require('firebase-admin/app');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue}=require('firebase-admin/firestore');
const {randomBytes}=require('node:crypto');
const items={hoodie:40,jacket:85,cap:35,crown:120,shades:55,spark:25,sunset:60,space:90};
function init(){if(!getApps().length){if(!process.env.FIREBASE_SERVICE_ACCOUNT)throw Error('Backend not configured');initializeApp({credential:cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT))})}return getFirestore()}
const respond=(status,body)=>({statusCode:status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify(body)});
exports.handler=async event=>{if(event.httpMethod!=='POST')return respond(405,{ok:false,error:'POST required'});try{let db=init(),token=event.headers.authorization?.replace(/^Bearer /i,'');if(!token)return respond(401,{ok:false,error:'Sign in first'});let verified=await getAuth().verifyIdToken(token),uid=verified.uid,body=JSON.parse(event.body||'{}');let userRef=db.collection('users').doc(uid),user=await userRef.get();
 if(body.action==='issue-invite'){if(verified.email!=='lukebalyasny.11@gmail.com'||verified.email_verified!==true||!user.exists||user.data().banned)return respond(403,{ok:false,error:'Creator only'});let email=String(body.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)return respond(400,{ok:false,error:'Enter a valid email'});let code=randomBytes(20).toString('hex');await db.collection('invites').doc(code).create({email,createdBy:uid,createdAt:FieldValue.serverTimestamp()});return respond(200,{ok:true,code,email})}
 if(!user.exists||user.data().banned)return respond(403,{ok:false,error:'Account unavailable'});
 if(body.action==='join-room'){let code=String(body.code||'');if(!/^[a-f0-9]{18}$/.test(code))return respond(400,{ok:false,error:'Invalid space code'});let ref=db.collection('rooms').doc(code);let snap=await ref.get();if(!snap.exists||snap.data().type!=='private'||snap.data().code!==code)return respond(404,{ok:false,error:'Space not found'});await ref.update({members:FieldValue.arrayUnion(uid)});return respond(200,{ok:true,name:snap.data().name})}
 if(body.action==='purchase'){let price=items[body.item];if(!price)return respond(400,{ok:false,error:'Unknown item'});await db.runTransaction(async tx=>{let snap=await tx.get(userRef),u=snap.data();if(u.banned||u.inventory?.includes(body.item)||u.credits<price)throw Error('Not enough credits or already owned');tx.update(userRef,{credits:u.credits-price,inventory:FieldValue.arrayUnion(body.item)})});return respond(200,{ok:true})}
 if(body.action==='join-event'){let eventId=String(body.eventId||'');if(!/^[A-Za-z0-9_-]{1,64}$/.test(eventId))return respond(400,{ok:false,error:'Invalid event'});let ref=db.collection('events').doc(eventId);await db.runTransaction(async tx=>{let [us,es]=await Promise.all([tx.get(userRef),tx.get(ref)]);if(!es.exists)throw Error('Event not found');let u=us.data(),e=es.data();if(u.banned||!Number.isInteger(e.fee)||e.fee<0||e.fee>500||e.attendees?.includes(uid)||u.credits<e.fee)throw Error('Already joined or not enough credits');tx.update(userRef,{credits:u.credits-e.fee});tx.update(ref,{attendees:FieldValue.arrayUnion(uid)})});return respond(200,{ok:true})}
 if(['ban','grant'].includes(body.action)){let code=String(body.code||''),role=code&&code===process.env.LUKE_ADMIN_CODE&&verified.email==='lukebalyasny.11@gmail.com'&&verified.email_verified===true?'Luke':code&&code===process.env.BAZ_ADMIN_CODE&&process.env.BAZ_ADMIN_EMAIL&&verified.email===process.env.BAZ_ADMIN_EMAIL&&verified.email_verified===true?'Baz':null;if(!role)return respond(403,{ok:false,error:'Wrong admin code'});let target=String(body.userId||'');if(!target||target===uid&&body.action==='ban')return respond(400,{ok:false,error:'Invalid member'});let ref=db.collection('users').doc(target),d=await ref.get();if(!d.exists)return respond(404,{ok:false,error:'Member not found'});if(body.action==='ban'){await ref.update({banned:true});return respond(200,{ok:true})}let amount=Number(body.amount);if(!Number.isInteger(amount)||amount<1||amount>500)return respond(400,{ok:false,error:'Grant must be 1-500'});await ref.update({credits:FieldValue.increment(amount)});return respond(200,{ok:true})}
 return respond(400,{ok:false,error:'Unknown action'})
 }catch(err){console.error(err);return respond(400,{ok:false,error:err.message||'Request failed'})}};
